### ISSUE TITLE
Request to add Index: CRYPTOCAP

### ISSUE THREAD

**Issue by phoneywc** [brian-the-dev/tradingview-list#1]
We have a few symbols that are useful:

TOTAL - Total crypto market cap
TOTAL2 - Total crypto market cap (excluding BTC)
TOTAL3 - Total crypto market cap (exclusing BTC and ETH)
TOTALDEFI - Total Defi market cap
OTHERS - Total crypto market cap (others)
![index cryptocap](https://user-images.githubusercontent.com/35164561/126086279-2f7f0a4e-9f26-4de9-8f21-3419f1f8f1d8.jpg)

**Comment by brian-the-dev** [comment]
Hi @phoneywc,

Unfortunately, those indices cannot be added to the database. Symbols that can be added should have a technicals tab. See this GIF for reference:

![](https://user-images.githubusercontent.com/40331046/125154071-4e43db00-e182-11eb-918f-5ffbd0fac04c.gif)

**Comment by phoneywc** [comment]
Thanks for clarifying, appreciate your reply :D
