### ISSUE TITLE
Russia MOEX

### ISSUE THREAD

**Issue by Gourieff** [brian-the-dev/tradingview-list#10]
Hello friends! Very like your project! Please add Russian MOEX symbols to your tradingview.db database!
Blue chips of MOEX are: 
---
MOEX
GAZP
VTBR
SBER
LKOH
ROSN
MTSS
RTKM
YNDX
NVTK
TCS
TCSG
PHOR
CHMF
NLMK
MAGN
PLZL
POLY
SNGS
SNGSP
TATN
MGNT
MVID
ALRS
AFLT
AFKS
AGRO
HYDR
FIVE
GMKN
RUAL
IRAO
---
Best regards!

**Comment by brian-the-dev** [comment]
Added Russia stock market.

![image](https://user-images.githubusercontent.com/40331046/145964098-632d94c5-fddb-4d42-bc04-90bd12923fc2.png)

I'll close this issue. If you have any questions, you can reply/comment on this issue.
