### ISSUE TITLE
Plase add Thailand to Trading view ta

### ISSUE THREAD

**Issue by kritthanit** [brian-the-dev/tradingview-list#11]
Hi, 
Can you add Thailand stock to trading view ta?

**Comment by brian-the-dev** [comment]
Added Thailand stock market.

![image](https://user-images.githubusercontent.com/40331046/145963608-9e41e7ea-b5b8-4924-83ad-5b80c95b50ab.png)

I'll close this issue. If you have any questions, you can reply/comment on this issue.

**Comment by kritthanit** [comment]
Thank you verymuch

ในวันที่ อ. 14 ธ.ค. 2021 เวลา 15:45 Brian ***@***.***>
เขียนว่า:
