### ISSUE TITLE
Add Symbol - BANKNIFTY for India ecxhange NSE

### ISSUE THREAD

**Issue by singhal110382** [brian-the-dev/tradingview-list#14]
Good Morning, 

Kindly add the new below details

Symbol = BANKNIFTY
Screener = India
Exchange = NSE

Thanks

**Comment by brian-the-dev** [comment]
Hi @singhal110382,

I'm sorry as I can't update the database right now. I don't know if my ISP or TradingView has problems but I can't access the API. As soon as I can access the API, I will notify you if I made changes to the database. Thanks for your patience.

**Comment by brian-the-dev** [comment]
Unfortunately, `BANKNIFTY` is a part of the index screener, which is currently not accessible through the API. All records in the database must be accessible in order for me to add them. I'm going to close this issue as it is currently unfixable. Don't hesitate to reply if you have any questions. Have a good one.
