### ISSUE TITLE
HK50

### ISSUE THREAD

**Issue by rararrr** [brian-the-dev/tradingview-list#15]
symbol="HK50",
exchange="GLOBALPRIME",
screener="cfd"

**Comment by brian-the-dev** [comment]
Hi @rararrr,

Currently, all indices are not available via the scanner API. HK50 is a part of indices, not CFD as it is not available in https://scanner.tradingview.com/cfd/scan. In order for a symbol to be added to the database, it must have a 'Technicals' tab, see this [example](https://github.com/brian-the-dev/python-tradingview-ta/issues/28#issuecomment-864880271).

I'm going to close this issue as it is unfixable from TradingView's side. If you have any questions don't hesitate to reply. Have a nice day.
