### ISSUE TITLE
SPX500USD Not Working

### ISSUE THREAD

**Issue by CerebralSeed** [brian-the-dev/tradingview-list#19]
I am trying to access Oanda's SPX500USD index. I've used the following:

handler=TA_Handler(symbol="SPX500USD", exchange="OANDA", screener="index", interval=Interval.INTERVAL_1_MINUTE)

However, it says the exchange doesn't exist. I've tried lower case, changing the screener to cfd, nothing seems to work. Page source shows: "symbol":"OANDA:SPX500USD","shortName":"SPX500USD"

TIA

**Comment by brian-the-dev** [comment]
Hello @CerebralSeed,

This is the wrong repository to submit your issue, the correct one is [brian-the-dev/python-tradingview-ta](https://github.com/brian-the-dev/python-tradingview-ta), as this is related to the usage of the library. However, you don't need to resubmit your issue, technical analysis for indices is not supported by tradingview-ta or even TradingView at this moment. For a detailed explanation, see [#84](https://github.com/brian-the-dev/python-tradingview-ta/issues/84#issuecomment-1047300624) on the correct repo. 

I'm going to close this issue. If you still have questions, don't hesitate to reply to this issue. Have a good one!
