### ISSUE TITLE
Lets add sweden STO exchange to the screener!

### ISSUE THREAD

**Issue by fgillet4** [brian-the-dev/tradingview-list#21]
I love using the python API for pulling TA, I am currently living and trading in sweden and would like to add STO (OMXSTO) and sweden to the list

**Comment by brian-the-dev** [comment]
Added in 4106305. Let me know if you have problems/questions related to this issue. Have a good one!

![image](https://user-images.githubusercontent.com/40331046/167601268-b84d2cbe-ee57-4e7b-ab15-717980b77687.png)

**Comment by fgillet4** [comment]
Hey Brian!

You are the man, its working!

Tradingview TA Version: 3.2.10
Enter asset symbol for OMXSTO Exchange (Ex. SAAB_B): SAAB_B
-----------------1 minute data----------------
SAAB_B
RSI: 38.80146619
Open: 395.3
Close: 395.3
Momentum: -1.4
MACD: -0.6307382
SELL
-----------------5 minute data----------------
SAAB_B
RSI: 40.65367318
Open: 395.5
Close: 395.3
Momentum: -0.8
MACD: -0.83320522
SELL
-----------------15 minute data----------------
SAAB_B
RSI: 31.44786325
Open: 395.5
Close: 395.3
Momentum: -5.7
MACD: -4.5732173
SELL
-----------------30 minute data----------------
SAAB_B
RSI: 31.46291693
Open: 397.6
Close: 395.3
Momentum: -18.9
MACD: -6.24404111
SELL
-----------------1 hour data----------------
SAAB_B
RSI: 24.61851591
Open: 396.1
Close: 395.3
Momentum: -23.1
MACD: -6.11168937
SELL
-----------------2 hour data----------------
SAAB_B
RSI: 26.37669821
Open: 398.3
Close: 395.3
Momentum: -26.5
MACD: -3.76009881
SELL
-----------------4 hour data----------------
SAAB_B
RSI: 34.28487476
Open: 410.6
Close: 395.3
Momentum: -24.5
MACD: 0.87454498
SELL
-----------------1 day data----------------
SAAB_B
RSI: 53.17549076
Open: 410.6
Close: 395.3
Momentum: 0.3
MACD: 16.61432341
NEUTRAL
-----------------1 week data----------------
SAAB_B
RSI: 68.61884329
Open: 418.5
Close: 395.3
Momentum: 92.3
MACD: 44.47518493
BUY
-----------------1 month data----------------
SAAB_B
RSI: 67.25284997
Open: 420
Close: 395.3
Momentum: 134.00001
MACD: 21.20042321
BUY

Here is a printout of the script, big thanks, lmk if you want the script!
