### ISSUE TITLE
Request to add Turkey to the Tradingview-TA.

### ISSUE THREAD

**Issue by onursahin93** [brian-the-dev/tradingview-list#22]
Could you please add Turkey (BIST) to the Tradingview-TA ?
Thanks.

**Comment by brian-the-dev** [comment]
Added Turkey market to https://tvdb.brianthe.dev.

![image](https://user-images.githubusercontent.com/40331046/170819093-1a259e1d-54d2-4342-a88e-421fd2c45cab.png)
