### ISSUE TITLE
Add screener

### ISSUE THREAD

**Issue by takoceto** [brian-the-dev/tradingview-list#23]
Please add Turkey's BIST stock to screener for using BIST's symbols.

**Comment by brian-the-dev** [comment]
Added Turkey market to https://tvdb.brianthe.dev.

![image](https://user-images.githubusercontent.com/40331046/170819093-1a259e1d-54d2-4342-a88e-421fd2c45cab.png)

**Comment by takoceto** [comment]
Thanks
