### ISSUE TITLE
Turkey (BIST100 - XU100) Screener

### ISSUE THREAD

**Issue by jokercraft** [brian-the-dev/tradingview-list#25]
Hi,
Thanks for letting me have this opportunity and suggesting one more screener be added to the database. Turkish stocks market! 
Tradingview Symbol: XU100
Country: Turkey

**Comment by brian-the-dev** [comment]
BIST100/XU100 is an index and therefore is unavailable. However, I added the Turkey market (individual stocks) to https://tvdb.brianthe.dev. 

![image](https://user-images.githubusercontent.com/40331046/170819093-1a259e1d-54d2-4342-a88e-421fd2c45cab.png)

**Comment by jokercraft** [comment]
Thanks!
