### ISSUE TITLE
please add Euronext and Germany

### ISSUE THREAD

**Issue by FBisschop** [brian-the-dev/tradingview-list#27]
Goodmorning
Thank you for this wonderful API. It works very well. However, I miss major European markets.
Would it be possible to add Euronext and Germany to your database?

Euronext is not really a country since it combines exchanges in Amsterdam (XAMS, AMS, AMS, ASX), Brussels (BRU, EBR, XBRU, ALXB), Paris (XPAR, ALXP, XMLI, PAR, EPA), Lisbon (ENXI, XLIS, ELI), Dublin (XMSM, XESM), Oslo (XOLS, XOAS, MERK), Milan

Germany: DAX, FRA, ETR

These were the exchanges that I could find that would be a good addition since they basically add a large part of Europe to the list.

Thank you

With kind regards

Francois
ef.roosegaardebisschop@gmail.com

**Comment by brian-the-dev** [comment]
Added Euronext and Germany: https://tvdb.brianthe.dev/

![image](https://user-images.githubusercontent.com/40331046/172606187-3435c994-34af-4fc9-b5e1-b38a132d7469.png)
![image](https://user-images.githubusercontent.com/40331046/172606236-50d2c61f-d611-4db1-8c54-eba9edb5e019.png)
