### ISSUE TITLE
no NQ1 data 

### ISSUE THREAD

**Issue by Suelinger** [brian-the-dev/tradingview-list#33]
hello, I wonder where can I found whether "NQ1" is contained in the symbol list?
thks so much!

**Comment by brian-the-dev** [comment]
Commit 1562b2a add supports for futures, including `NQ1!`. Check https://tvdb.brianthe.dev/.

**Comment by Suelinger** [comment]
Thank you a lot !!! It will help my study so much. Wish you all the best.













在 2022-07-06 20:49:41，"Brian" ***@***.***> 写道：

Commit 1562b2a add supports for futures, including NQ1!. Check https://tvdb.brianthe.dev/.
