### ISSUE TITLE
Adding "Hong Kong" stock data in the api

### ISSUE THREAD

**Issue by wttwoo** [brian-the-dev/tradingview-list#37]
Hi Team,
Is it possible to add the stock information from Hong Kong Market to your API?
Regards,
Sharon

**Comment by brian-the-dev** [comment]
[Done](https://tvdb.brianthe.dev/).

![image](https://user-images.githubusercontent.com/40331046/184781195-5757dfeb-4542-4a1d-bbbe-2abc658f12d0.png)
