### ISSUE TITLE
What is the symbol for banknifty and nifty50 index

### ISSUE THREAD

**Issue by anandmanika** [brian-the-dev/tradingview-list#42]
TA_Handler(
                symbol= 'BANKBEES', 
                screener = 'INDIA',
                exchange= 'NSE',
                interval=Interval.INTERVAL_15_MINUTES
            )

What should be the symbol for nifty50 and banknifty indices

**Comment by brian-the-dev** [comment]
Duplicate of #14, #29, #30, #38, #39.
