### ISSUE TITLE
many symbols are not found

### ISSUE THREAD

**Issue by akash213213** [brian-the-dev/tradingview-list#43]
Hi, 
from screener 'INDIA'  and exchange 'NSE' many important symbols are missing . Please add below symbols
'BANKNIFTY'
'NIFTY'
'RELIANCE'

request you to add and confirm

**Comment by brian-the-dev** [comment]
Duplicate of https://github.com/brian-the-dev/tradingview-list/issues/14, https://github.com/brian-the-dev/tradingview-list/issues/29, https://github.com/brian-the-dev/tradingview-list/issues/30, https://github.com/brian-the-dev/tradingview-list/issues/38, https://github.com/brian-the-dev/tradingview-list/issues/39.

**Comment by akash213213** [comment]
Hi brian , can it be done?

**Comment by brian-the-dev** [comment]
Please read the readme:

> Please note that indices are not supported by tradingview-ta, this is a limitation from TradingView's API, not the library.
