### ISSUE TITLE
can't find symbol 

### ISSUE THREAD

**Issue by klllo** [brian-the-dev/tradingview-list#44]
i can't find TSL3 in https://tvdb.brianthe.dev/ but i can find it in trading view. How come?

**Comment by brian-the-dev** [comment]
Only assets with the "Technicals" tab are compatible with python-tradingview-ta and tradingview-list. Unfortunately, TSL3 isn't one of them. There's no known workaround for now, so I will close this issue. For details, see the comparison below:
![image](https://user-images.githubusercontent.com/40331046/192269628-f1057e00-f002-45bd-8d7a-e2a5ad023a65.png)
![image](https://user-images.githubusercontent.com/40331046/192269711-c51712a5-adcd-4081-9d56-1606479c3ab4.png)
