### ISSUE TITLE
Unable to import indices data from tradingview_ta

### ISSUE THREAD

**Issue by ssharmatrading** [brian-the-dev/tradingview-list#46]
Hi Brian,

There is no tickers for Indices like 'NIFTY50', 'BANKNIFTY' and other indices like these for Indian market.

**Comment by brian-the-dev** [comment]
Please re-read README.md:

> Before filing an issue, make sure that the symbol(s) you are requesting are NOT index/indices, such as BANKNIFTY and NIFTY50. This has been requested numerous times (#14, #29, #30, #38, #39); however, the limitation is solely related to TradingView rather than python-tradingview-ta.

I'm closing this issue as it's a duplicate.
