### ISSUE TITLE
Add important symbols for Vietnam market

### ISSUE THREAD

**Issue by leloi01** [brian-the-dev/tradingview-list#49]
Hi Managers,

As I check from https://tvdb.brianthe.dev, some important symbols are not existed for Vietnam stock market.
So could you add those ones, that would be very helpful:
- VN30 Future 1 month, 2 months, 3 months, 9 months
- VN index, VN30 Index, HNX index, HNX 30 index

Thank you very much!

**Comment by brian-the-dev** [comment]
Please re-read the README.md:

> Before filing an issue, make sure that the symbol(s) you are requesting are NOT index/indices, such as BANKNIFTY and NIFTY50. This has been requested numerous times (#14, #29, #30, #38, #39); however, the limitation is solely related to TradingView rather than python-tradingview-ta.
