### ISSUE TITLE
FTX exchange

### ISSUE THREAD

**Issue by sinaFa** [brian-the-dev/tradingview-list#5]
Hi,
Is it possible to cover FTX exchange as well for the crypto screener?
Thanks!

**Comment by brian-the-dev** [comment]
Added FTX exchange.

https://tvdb.brianthe.dev/

![image](https://user-images.githubusercontent.com/40331046/139567772-59ca0269-ff44-4696-96dc-ce5ce1e90367.png)

**Comment by sinaFa** [comment]
Great! Thanks a lot!!
