### ISSUE TITLE
Canada TSX

### ISSUE THREAD

**Issue by sxbdouglas** [brian-the-dev/tradingview-list#50]
Hi folks.
I saw Canada TSX is missing from tradingview list.
Could you add it?

Best,
Douglas.

**Comment by brian-the-dev** [comment]
Done 👍👍

![image](https://user-images.githubusercontent.com/40331046/217839726-76878600-1c4e-474d-8a8e-34f55c81f171.png)

**Comment by sxbdouglas** [comment]
Thanks Brian.
Great work!

Em quinta-feira, 9 de fevereiro de 2023, Brian ***@***.***>
escreveu:
