### ISSUE TITLE
XAUUSD

### ISSUE THREAD

**Issue by LPAlly** [brian-the-dev/tradingview-list#7]
Hi, could the XAUUSD on the FXCM be add please

**Comment by brian-the-dev** [comment]
HI @LPAlly,

Unfortunately, that is impossible as there is no technicals tab on their site. Getting information about a ticker is only possible when there is a technicals tab. See [this issue](https://github.com/brian-the-dev/python-tradingview-ta/issues/28#issuecomment-864880271) for reference. I'm going to close this issue as it's currently unfixable.

Thank you and have a nice day.
