### ISSUE TITLE
how to access ASX stocks? 

### ISSUE THREAD

**Issue by aspiringguru** [brian-the-dev/tradingview-list#8]
I tried searching for some ASX stocks on https://tvdb.brianthe.dev/
downloaded the tradingview.db file and looked into the database.

select * from tv where exchange='ASX';

only found one stock.

screener  exchange  symbol  desc
--------  --------  ------  -----------
cfd       ASX       XJO     S&P/ASX 200

poking around the db reveals a small subset of the potential stock listings are available.
select distinct exchange, count(*) from tv group by exchange order by exchange;

#------------------------------------------------------------------------------------
from tradingview_ta import TA_Handler, Interval, Exchange
tesla = TA_Handler(
    symbol="TSLA",
    screener="america",
    exchange="NASDAQ",
    interval=Interval.INTERVAL_1_DAY
)
print(tesla.get_analysis().summary)
#------------------------------------------------------------------------------------
is it possible to extend the list of stocks in the db so I can run a screener over ASX stocks?

**Comment by brian-the-dev** [comment]
Hi @aspiringguru,

I've just added the Australian stock market. I'm going to close this issue, feel free to reply if you still have any questions. Have a good one.

https://tvdb.brianthe.dev/

![image](https://user-images.githubusercontent.com/40331046/140679455-360250ba-cdef-4183-af7b-ee0d0af612bb.png)
